name: stratosphere
version: "0.31.0"
synopsis: EDSL for AWS CloudFormation
description: EDSL for AWS CloudFormation
category: AWS, Cloud
maintainer: David Reaver
stability: experimental
license: MIT
license-file: LICENSE.md

github: frontrowed/stratosphere

extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - base >= 4.8 && < 5
  - aeson >= 0.11
  - aeson-pretty >= 0.8
  - bytestring
  - containers
  - hashable
  - lens >= 4.5
  - template-haskell >= 2.0
  - text >= 1.1
  - unordered-containers >= 0.2

flags:
  library-only:
    description: "Don't compile examples"
    default: true
    manual: true

library:
  source-dirs:
    - library
    - library-gen
  ghc-options: -Wall

executables:
  auto-scaling-group:
    main: auto-scaling-group.hs
    source-dirs: examples
    dependencies: stratosphere
    ghc-options: -Wall
    when:
      - condition: flag(library-only)
        buildable: false
  rds-master-replica:
    main: rds-master-replica.hs
    source-dirs: examples
    dependencies: stratosphere
    ghc-options: -Wall
    when:
      - condition: flag(library-only)
        buildable: false
  simple-lambda:
    main: simple-lambda.hs
    source-dirs: examples
    dependencies: stratosphere
    ghc-options: -Wall
    when:
      - condition: flag(library-only)
        buildable: false
  s3-copy:
    main: s3-copy.hs
    source-dirs: examples
    dependencies: stratosphere
    ghc-options: -Wall
    when:
      - condition: flag(library-only)
        buildable: false

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests
    dependencies:
      - base
      - stratosphere
      - hspec
      - hspec-discover
